# Generated by Django 4.1 on 2022-08-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
